package bpms.formmodeler;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FormRuntimeTest_DataObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String stringTextBox;

	private java.util.List<java.lang.String> stringMultipleSelector;

	private java.util.List<java.lang.String> stringMultipleInput;

	private java.lang.String stringTextArea;

	private java.lang.Integer integerRadioGroup;

	private java.lang.String stringListBox;

	private java.lang.Double doubleSlider;

	private java.util.List<bpms.formmodeler.FormRuntimeTest_NestedDataObject> multipleSubform;

	public FormRuntimeTest_DataObject() {
	}

	public java.lang.String getStringTextBox() {
		return this.stringTextBox;
	}

	public void setStringTextBox(java.lang.String stringTextBox) {
		this.stringTextBox = stringTextBox;
	}

	public java.util.List<java.lang.String> getStringMultipleSelector() {
		return this.stringMultipleSelector;
	}

	public void setStringMultipleSelector(
			java.util.List<java.lang.String> stringMultipleSelector) {
		this.stringMultipleSelector = stringMultipleSelector;
	}

	public java.util.List<java.lang.String> getStringMultipleInput() {
		return this.stringMultipleInput;
	}

	public void setStringMultipleInput(
			java.util.List<java.lang.String> stringMultipleInput) {
		this.stringMultipleInput = stringMultipleInput;
	}

	public java.lang.String getStringTextArea() {
		return this.stringTextArea;
	}

	public void setStringTextArea(java.lang.String stringTextArea) {
		this.stringTextArea = stringTextArea;
	}

	public java.lang.Integer getIntegerRadioGroup() {
		return this.integerRadioGroup;
	}

	public void setIntegerRadioGroup(java.lang.Integer integerRadioGroup) {
		this.integerRadioGroup = integerRadioGroup;
	}

	public java.lang.String getStringListBox() {
		return this.stringListBox;
	}

	public void setStringListBox(java.lang.String stringListBox) {
		this.stringListBox = stringListBox;
	}

	public java.lang.Double getDoubleSlider() {
		return this.doubleSlider;
	}

	public void setDoubleSlider(java.lang.Double doubleSlider) {
		this.doubleSlider = doubleSlider;
	}

	public java.util.List<bpms.formmodeler.FormRuntimeTest_NestedDataObject> getMultipleSubform() {
		return this.multipleSubform;
	}

	public void setMultipleSubform(
			java.util.List<bpms.formmodeler.FormRuntimeTest_NestedDataObject> multipleSubform) {
		this.multipleSubform = multipleSubform;
	}

	public FormRuntimeTest_DataObject(
			java.lang.String stringTextBox,
			java.util.List<java.lang.String> stringMultipleSelector,
			java.util.List<java.lang.String> stringMultipleInput,
			java.lang.String stringTextArea,
			java.lang.Integer integerRadioGroup,
			java.lang.String stringListBox,
			java.lang.Double doubleSlider,
			java.util.List<bpms.formmodeler.FormRuntimeTest_NestedDataObject> multipleSubform) {
		this.stringTextBox = stringTextBox;
		this.stringMultipleSelector = stringMultipleSelector;
		this.stringMultipleInput = stringMultipleInput;
		this.stringTextArea = stringTextArea;
		this.integerRadioGroup = integerRadioGroup;
		this.stringListBox = stringListBox;
		this.doubleSlider = doubleSlider;
		this.multipleSubform = multipleSubform;
	}

}