package bpms.formmodeler;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FormRuntimeTest_NestedDataObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Float floatRadioGroup;

	private java.time.LocalDateTime localDateTimeDatePicker;

	public FormRuntimeTest_NestedDataObject() {
	}

	public java.lang.Float getFloatRadioGroup() {
		return this.floatRadioGroup;
	}

	public void setFloatRadioGroup(java.lang.Float floatRadioGroup) {
		this.floatRadioGroup = floatRadioGroup;
	}

	public java.time.LocalDateTime getLocalDateTimeDatePicker() {
		return this.localDateTimeDatePicker;
	}

	public void setLocalDateTimeDatePicker(
			java.time.LocalDateTime localDateTimeDatePicker) {
		this.localDateTimeDatePicker = localDateTimeDatePicker;
	}

	public FormRuntimeTest_NestedDataObject(java.lang.Float floatRadioGroup,
			java.time.LocalDateTime localDateTimeDatePicker) {
		this.floatRadioGroup = floatRadioGroup;
		this.localDateTimeDatePicker = localDateTimeDatePicker;
	}

}